### ISSUE TITLE
fix: 기능 테스트 후 정리한 에러 수정

### ISSUE THREAD

**Issue by Kimkyungmin123** [20thcenturygangsta/cassette-client#103]
## Description
[03.05 디버깅 테스트](https://www.notion.so/12-d0abbdf17a1844ebb1457f3bcce4d83b?p=7a13480d2c9a42059162880d669838a9&pm=s)에서 발견한 에러 수정하기

## Todo
- [x] 탈퇴 시,로그인 되어 있던 다른 브라우저에 들어가면 홈으로 리다이렉트 
- [x] background image 화면 비율에 따라 짤리는 에러 
- [x] 페이지 bottom 일괄적으로  일정 값 주기 (현재 디바이스에 따라 페이지 하단과 딱 붙어 있는 경우 발생)
- [x] 음성 재생 중에 일시 정지하면 일시정지 아이콘이 제대로 노출되지 않는 에러 
- [x]  탈퇴 페이지에서 체크 박스에 체크할 때, check svg를 때때로 불러오지 못하는 에러
- [x] 음성 파일 재생중일 때 테이프 애니메이션 추가
- [x] 트렉 이동 시 progress bar 초기화 안되는 에러
- [x] 일시 정지 중, progress bar 직접 이동 시 아이콘 바뀌는(`play` -> `pause`) 에러
- [x] 일시 정시 중, progress bar 직접 이동 시 테이프 애니메이션 작동하는 에러
- [x] 일시 정지 후 두 번 클릭해야 다시 재생되는 에러
- [x] audio 비활성화시에도 progressbar에 접근되는 에러
